name: Github API
on: workflow_dispatch
jobs:
  get-contributors:
    runs-on: ubuntu-latest
    steps:
      - run: node .github/actions/get-contributors.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
