name: Github API
on: workflow_dispatch
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  get-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
      - run: node .github/actions/get-contributors.js
